package Dungeon;

import java.util.Random;

public class MagicTables {

	public static String A()
	{
		int x = roll(100,1);
		String y ="A";
		if (x <= 50)
			y = "Potion of Healing";
		else if(x <= 60)
			y = "Spell scroll (cantrip)";
		else if(x <= 70)
			y = "Potion of climbing";
		else if(x <= 90)
			y = "Spell scroll (1st level)";
		else if(x <= 94)
			y = "Spell scroll (2nd level)";
		else if(x <= 98)
			y = "Potion of greater healing";
		else if(x <= 99)
			y = "Bag of holding";
		else 
			y = "Driftglobe";
		return y;
	}
	public static String B()
	{
		int x = roll(100,1);
		String y ="B";
		if (x <= 15)
			y = "Potion of greater healing";
		else if(x <= 22)
			y = "Potion of fire breath";
		else if(x <= 29)
			y = "Potion of resistance";
		else if(x <= 34)
			y = "Ammunition, +1";
		else if(x <= 39)
			y = "Potion of animal friendship";
		else if(x <= 44)
			y = "Potion of hill giant strength";
		else if(x <= 49)
			y = "Potion of growth";
		else if(x <= 54)
			y = "Potion of water breathing";
		else if(x <= 59)
			y = "Spell scroll (2nd level)";
		else if(x <= 64)
			y = "Spell scroll (3rd level)";
		else if(x <= 67)
			y = "Bag of holding";
		else if(x <= 70)
			y = "Keoghtom's ointment";
		else if(x <= 73)
			y = "Oil of slipperiness";
		else if(x <= 75)
			y = "Dust of disappearance";
		else if(x <= 77)
			y = "Dust of dryness";
		else if(x <= 79)
			y = "Dust of sneezing and choking";
		else if(x <= 81)
			y = "Elemental gem";
		else if(x <= 83)
			y = "Philter of love";
		else if(x <= 84)
			y = "Alchemy jug";
		else if(x <= 85)
			y = "Cap of water breathing";
		else if(x <= 86)
			y = "Cloak of the manta ray";
		else if(x <= 87)
			y = "Driftglobe";
		else if(x <= 88)
			y = "Goggles of night";
		else if(x <= 89)
			y = "Helm of comprehending languages";
		else if(x <= 90)
			y = "Immovable rod";
		else if(x <= 91)
			y = "Lantern of revealing";
		else if(x <= 92)
			y = "Mariner's armor";
		else if(x <= 93)
			y = "Mithral armor";
		else if(x <= 94)
			y = "Potion of poison";
		else if(x <= 95)
			y = "Ring of swimming";
		else if(x <= 96)
			y = "Robe of useful items";
		else if(x <= 97)
			y = "Rope of climbing ";
		else if(x <= 98)
			y = "Saddle of the cavalier ";
		else if(x <= 99)
			y = "Wand of magic detection";
		else
			y = "Wand of secrets";
		return y;
	}
	public static String C()
	{
		int x = roll(100,1);
		String y ="C";
		if (x <= 15)
			y = "Potion of superior healing ";
		else if(x <= 22)
			y = "Spell scroll (4th level)";
		else if(x <= 27)
			y = "Ammunition +2";
		else if(x <= 32)
			y = "Potion of clairvoyance";
		else if(x <= 37)
			y = "Potion of diminution";
		else if(x <= 42)
			y = "Potion of gaseous form";
		else if(x <= 47)
			y = "Potion of frost giant strength";
		else if(x <= 52)
			y = "Potion of stone giant strength ";
		else if(x <= 57)
			y = "Potion of heroism";
		else if(x <= 62)
			y = "Potion of invulnerability";
		else if(x <= 67)
			y = "Potion of mind reading";
		else if(x <= 72)
			y = "Spell scroll (5th level)";
		else if(x <= 75)
			y = "Elixir of health";
		else if(x <= 78)
			y = "Oil of etherealness";
		else if(x <= 81)
			y = "Potion of fire giant strength ";
		else if(x <= 84)
			y = "Quaal's feather token";
		else if(x <= 87)
			y = "Scroll of protection";
		else if(x <= 89)
			y = "Bag of beans";
		else if(x <= 91)
			y = "Bead of force";
		else if(x <= 92)
			y = "Chime of opening";
		else if(x <= 93)
			y = "Decanter of endless water";
		else if(x <= 94)
			y = "Eyes of minute seeing";
		else if(x <= 95)
			y = "Folding boat";
		else if(x <= 96)
			y = "Heward's handy haversack";
		else if(x <= 97)
			y = "Horseshoes of speed";
		else if(x <= 98)
			y = "Necklace of fireballs";
		else if(x <= 99)
			y = "Periapt of health";
		else
			y = "Sending stones";
		return y;
	}
	public static String D()
	{
		int x = roll(100,1);
		String y ="D";
		if (x <= 20)
			y = "Potion of supreme healing";
		else if(x <= 30)
			y = "Potion of invisibility";
		else if(x <= 40)
			y = "Potion of speed";
		else if(x <= 50)
			y = "Spell scroll (6th level)";
		else if(x <= 57)
			y = "Spell scroll (7th level)";
		else if(x <= 62)
			y = "Ammunition +3";
		else if(x <= 67)
			y = "Oil of sharpness";
		else if(x <= 72)
			y = "Potion of flying";
		else if(x <= 77)
			y = "Potion of cloud giant strength";
		else if(x <= 82)
			y = "Potion of longevity";
		else if(x <= 87)
			y = "Potion of vitality";
		else if(x <= 92)
			y = "Spell scroll (8th level)";
		else if(x <= 95)
			y = "Horseshoes of a zephyr";
		else if(x <= 98)
			y = "Nolzur's marvelous pigments";
		else if(x <= 99)
			y = "Bag of devouring";
		else
			y = "Portable hole";

		return y;
	}
	public static String E()
	{
		int x = roll(100,1);
		String y ="E";
		if (x <= 30)
			y = "Spell scroll (8th level)";
		else if(x <= 55)
			y = "Potion of storm giant strength";
		else if(x <= 70)
			y = "Potion of supreme healing";
		else if(x <= 85)
			y = "Spell scroll (9th level)";
		else if(x <= 93)
			y = "Universal solvent";
		else if(x <= 98)
			y = "Arrow of slaying";
		else
			y = "Sovereign glue";
		return y;
	}
	public static String F()
	{
		int x = roll(100,1);
		String y ="F";
		if (x <= 15)
			y = "Weapon +1";
		else if(x <= 18)
			y = "Shield +1";
		else if(x <= 21)
			y = "Sentinel shield";
		else if(x <= 23)
			y = "Amulet of proof against detection and location";
		else if(x <= 25)
			y = "Boots of elvenkind";
		else if(x <= 27)
			y = "Boots of striding and springing";
		else if(x <= 29)
			y = "Bracers of archery";
		else if(x <= 31)
			y = "Brooch of shielding";
		else if(x <= 33)
			y = "Broom of flying";
		else if(x <= 35)
			y = "Cloak of elvenkind";
		else if(x <= 37)
			y = "Cloak of protection";
		else if(x <= 39)
			y = "Gauntlets of ogre power";
		else if(x <= 41)
			y = "Hat of disguise";
		else if(x <= 43)
			y = "Javelin of lightning";
		else if(x <= 45)
			y = "Pearl of power";
		else if(x <= 47)
			y = "Rod of the pact keeper +1";
		else if(x <= 49)
			y = "Slippers of spider climbing";
		else if(x <= 51)
			y = "Staff of the adder";
		else if(x <= 53)
			y = "Staff of the python";
		else if(x <= 55)
			y = "Sword of vengeance";
		else if(x <= 57)
			y = "Trident of fish command";
		else if(x <= 59)
			y = "Wand of magic missiles";
		else if(x <= 61)
			y = "Wand of the war mage +1";
		else if(x <= 63)
			y = "Wand of web";
		else if(x <= 65)
			y = "Weapon of warning";
		else if(x <= 66)
			y = "Adamantine armor (chain mail)";
		else if(x <= 67)
			y = "Adamantine armor (chain shirt)";
		else if(x <= 68)
			y = "Adamantine armor (scale mail)";
		else if(x <= 69)
			y = "Bag of tricks (gray)";
		else if(x <= 70)
			y = "Bag of tricks (rust)";
		else if(x <= 71)
			y = "Bag of tricks (tan)";
		else if(x <= 72)
			y = "Boots of the winterlands";
		else if(x <= 73)
			y = "Circlet of blasting";
		else if(x <= 74)
			y = "Deck of illusions";
		else if(x <= 75)
			y = "Eversmoking bottle";
		else if(x <= 76)
			y = "Eyes of charming";
		else if(x <= 77)
			y = "Eyes of the eagle";
		else if(x <= 78)
			y = "Figurine of wondrous power (silver raven)";
		else if(x <= 79)
			y = "Gem of brightness";
		else if(x <= 80)
			y = "Gloves of missile snaring";
		else if(x <= 81)
			y = "Gloves of swimming and climbing";
		else if(x <= 82)
			y = "Gloves of thievery";
		else if(x <= 83)
			y = "Headband of intellect";
		else if(x <= 84)
			y = "Helm of telepathy";
		else if(x <= 85)
			y = "Instrument of the bards (Doss lute)";
		else if(x <= 86)
			y = "Instrument of the bards (Fochlucan bandore)";
		else if(x <= 87)
			y = "Instrument of the bards (Mac-Fuimidh cittern)";
		else if(x <= 88)
			y = "Medallion of thoughts";
		else if(x <= 89)
			y = "Necklace of adaptation";
		else if(x <= 90)
			y = "Periapt of wound closure";
		else if(x <= 91)
			y = "Pipes of haunting";
		else if(x <= 92)
			y = "Pipes of the sewers";
		else if(x <= 93)
			y = "Ring of jumping";
		else if(x <= 94)
			y = "Ring of mind shielding";
		else if(x <= 95)
			y = "Ring of warmth";
		else if(x <= 96)
			y = "Ring of water walking";
		else if(x <= 97)
			y = "Quiver of Ehlonna";
		else if(x <= 98)
			y = "Stone of good luck";
		else if(x <= 99)
			y = "Wind fan";
		else 
			y = "Winged boots";
		return y;
	}
	public static String G()
	{
		int x = roll(100,1);
		int z = roll(8,1);
		String y ="G";
		if (x <= 11)
			y = "Weapon +2";
		else if(x <= 14)
		{
			y = "Figurine of wondrous power: ";
			if (z <= 1)
				y += "Bronze griffon";
			else if(z <= 2)
				y += "Ebony fly";
			else if(z <= 3)
				y += "Golden lions";
			else if(z <= 4)
				y += "Ivory goats";
			else if(z <= 5)
				y += "Marble elephant";
			else if(z <= 7)
				y += "Onyx dog";
			else 
				y += "Serpentine owl ";
		}
		else if(x <= 15)
			y = "Adamantine armor (breastplate)";
		else if(x <= 16)
			y = "Adamantine armor (splint)";
		else if(x <= 17)
			y = "Amulet of health";
		else if(x <= 18)
			y = "Armor of vulnerability";
		else if(x <= 19)
			y = "Arrow-catching shield";
		else if(x <= 20)
			y = "Belt of dwarvenkind";
		else if(x <= 21)
			y = "Belt of hill giant strength";
		else if(x <= 22)
			y = "Berserker axe";
		else if(x <= 23)
			y = "Boots of levitation";
		else if(x <= 24)
			y = "Boots of speed";
		else if(x <= 25)
			y = "Bowl of commanding water elementals";
		else if(x <= 26)
			y = "Bracers of defense";
		else if(x <= 27)
			y = "Brazier of commanding fire elementals";
		else if(x <= 28)
			y = "Cape of the mountebank";
		else if(x <= 29)
			y = "Censer of controlling air elementals";
		else if(x <= 30)
			y = "Armor +1 chain mail";
		else if(x <= 31)
			y = "Armor of resistance (chain mail)";
		else if(x <= 32)
			y = "Armor +1 chain shirt";
		else if(x <= 33)
			y = "Armor of resistance (chain shirt)";
		else if(x <= 34)
			y = "Cloak of displacement";
		else if(x <= 35)
			y = "Cloak of the bat";
		else if(x <= 36)
			y = "Cube afforce";
		else if(x <= 37)
			y = "Daern's instant fortress";
		else if(x <= 38)
			y = "Dagger of venom";
		else if(x <= 39)
			y = "Dimensional shackles";
		else if(x <= 40)
			y = "Dragon slayer";
		else if(x <= 41)
			y = "Elven chain";
		else if(x <= 42)
			y = "Flame tongue";
		else if(x <= 43)
			y = "Gem of seeing";
		else if(x <= 44)
			y = "Giant slayer";
		else if(x <= 45)
			y = "Clamoured studded leather";
		else if(x <= 46)
			y = "Helm of teleportation";
		else if(x <= 47)
			y = "Horn of blasting";
		else if(x <= 48)
		{
			z = roll(100,1);
			if (z<= 50)
				y = "Horn of Valhalla (silver)";
			else
				y = "Horn of Valhalla (Brass)";
		}
		else if(x <= 49)
			y = "Instrument of the bards (Canaith mandolin)";
		else if(x <= 50)
			y = "Instrument ofthe bards (Cii lyre)";
		else if(x <= 51)
			y = "Ioun stone (awareness)";
		else if(x <= 52)
			y = "Ioun stone (protection)";
		else if(x <= 53)
			y = "Ioun stone (reserve)";
		else if(x <= 54)
			y = "Ioun stone (sustenance) ";
		else if(x <= 55)
			y = "Iron bands of Bilarro ";
		else if(x <= 56)
			y = "Armor +1 leather";
		else if(x <= 57)
			y = "Armor of resistance (leather)";
		else if(x <= 58)
			y = "Mace of disruption";
		else if(x <= 59)
			y = "Mace of smiting";
		else if(x <= 60)
			y = "Mace of terror";
		else if(x <= 61)
			y = "Mantle of spell resistance";
		else if(x <= 62)
			y = "Necklace of prayer beads";
		else if(x <= 63)
			y = "Periapt of proof against poison";
		else if(x <= 64)
			y = "Ring of animal influence";
		else if(x <= 65)
			y = "Ring of evasion";
		else if(x <= 66)
			y = "Ring of feather falling";
		else if(x <= 67)
			y = "Ring of free action";
		else if(x <= 68)
			y = "Ring of protection";
		else if(x <= 69)
			y = "Ring of resistance";
		else if(x <= 70)
			y = "Ring of spell storing";
		else if(x <= 71)
			y = "Ring of the ram";
		else if(x <= 72)
			y = "Ring of X-ray vision";
		else if(x <= 73)
			y = "Robe of eyes";
		else if(x <= 74)
			y = "Rod of rulership";
		else if(x <= 75)
			y = "Rod of the pact keeper +2";
		else if(x <= 76)
			y = "Rope of entanglement";
		else if(x <= 77)
			y = "Armor +1 scale mail";
		else if(x <= 78)
			y = "Armor of resistance (scale mail)";
		else if(x <= 79)
			y = "Shield +2";
		else if(x <= 80)
			y = "Shield of missile attraction";
		else if(x <= 81)
			y = "Staff of charming";
		else if(x <= 82)
			y = "Staff of healing";
		else if(x <= 83)
			y = "Staff of swarming insects";
		else if(x <= 84)
			y = "Staff of the woodlands";
		else if(x <= 85)
			y = "Staff of withering";
		else if(x <= 86)
			y = "Stone of controlling earth elementals";
		else if(x <= 87)
			y = "Sun blade";
		else if(x <= 88)
			y = "Sword of life stealing";
		else if(x <= 89)
			y = "Sword of wounding";
		else if(x <= 90)
			y = "Tentacle rod";
		else if(x <= 91)
			y = "Vicious weapon";
		else if(x <= 92)
			y = "Wand of binding";
		else if(x <= 93)
			y = "Wand of enemy detection";
		else if(x <= 94)
			y = "Wand of fear";
		else if(x <= 95)
			y = "Wand of fireballs";
		else if(x <= 96)
			y = "Wand of lightning bolts";
		else if(x <= 97)
			y = "Wand of paralysis";
		else if(x <= 98)
			y = "Wand of the war mage +2";
		else if(x <= 99)
			y = "Wand of wonder";
		else 
			y = "Wings of flying";
		return y;
	}
	public static String H()
	{
		int x = roll(100,1);
		int z = roll(100,1);
		String y ="H";
		if (x <= 10)
			y = "Weapon +3";
		else if(x <= 12)
			y = "Amulet of the planes";
		else if(x <= 14)
			y = "Carpet of flying";
		else if(x <= 16)
			y = "Crystal ball (very rare version)";
		else if(x <= 18)
			y = "Ring of regeneration";
		else if(x <= 20)
			y = "Ring of shooting stars";
		else if(x <= 22)
			y = "Ring of telekinesis";
		else if(x <= 24)
			y = "Robe of scintillating colors";
		else if(x <= 26)
			y = "Robe of stars";
		else if(x <= 28)
			y = "Rod of absorption";
		else if(x <= 30)
			y = "Rod of alertness";
		else if(x <= 32)
			y = "Rod of security";
		else if(x <= 34)
			y = "Rod of the pact keeper +3";
		else if(x <= 36)
			y = "Scimitar of speed";
		else if(x <= 38)
			y = "Shield +3";
		else if(x <= 40)
			y = "Staff of fire";
		else if(x <= 42)
			y = "Staff of frost";
		else if(x <= 44)
			y = "Staff of power";
		else if(x <= 46)
			y = "Staff of striking ";
		else if(x <= 48)
			y = "Staff of thunder and lightning";
		else if(x <= 50)
			y = "Sword of sharpness";
		else if(x <= 52)
			y = "Wand of polymorph";
		else if(x <= 54)
			y = "Wand of the war mage +3";
		else if(x <= 55)
			y = "Adamantine armor (half plate)";
		else if(x <= 56)
			y = "Adamantine armor (plate)";
		else if(x <= 57)
			y = "Animated shield";
		else if(x <= 58)
			y = "Belt of fire giant strength";
		else if(x <= 59)
		{
			if(z<= 50)
				y = "Belt of frost giant strength";
			else
				y = "Belt of stone giant strength";
		}
		else if(x <= 60)
			y = "Armor +1 breastplate";
		else if(x <= 61)
			y = "Armor of resistance (breastplate)";
		else if(x <= 62)
			y = "Candle of invocation";
		else if(x <= 63)
			y = "Armor +2 chain mail";
		else if(x <= 64)
			y = "Armor +2 chain shirt";
		else if(x <= 65)
			y = "Cloak of arachnida";
		else if(x <= 66)
			y = "Dancing sword";
		else if(x <= 67)
			y = "Demon armor";
		else if(x <= 68)
			y = "Dragon scale mail";
		else if(x <= 69)
			y = "Dwarven plate";
		else if(x <= 70)
			y = "Dwarven thrower";
		else if(x <= 71)
			y = "Efreeti bottle";
		else if(x <= 72)
			y = "Figurine of wondrous power (obsidian steed)";
		else if(x <= 73)
			y = "Frost brand";
		else if(x <= 74)
			y = "Helm of brilliance";
		else if(x <= 75)
			y = "Horn ofValhalla (bronze)";
		else if(x <= 76)
			y = "Instrument of the bards (Anstruth harp)";
		else if(x <= 77)
			y = "Ioun stone(absorption)";
		else if(x <= 78)
			y = "Ioun stone(agility)";
		else if(x <= 79)
			y = "Ioun stone(fortitude)";
		else if(x <= 80)
			y = "Ioun stone(insight)";
		else if(x <= 81)
			y = "Ioun stone(intellect)";
		else if(x <= 82)
			y = "Ioun stone(leadership)";
		else if(x <= 83)
			y = "Ioun stone(strength)";
		else if(x <= 84)
			y = "Armor +2 leather";
		else if(x <= 85)
			y = "Manual of bodily health";
		else if(x <= 86)
			y = "Manual of gainful exercise";
		else if(x <= 87)
			y = "Manual of golems";
		else if(x <= 88)
			y = "Manual of quickness of action";
		else if(x <= 89)
			y = "Mirror of life trapping";
		else if(x <= 90)
			y = "Nine lives stealer";
		else if(x <= 91)
			y = "Oathbow";
		else if(x <= 92)
			y = "Armor +2 scale mail";
		else if(x <= 93)
			y = "Spellguard shield";
		else if(x <= 94)
			y = "Armor +1 splint";
		else if(x <= 95)
			y = "Armor of resistance (splint)";
		else if(x <= 96)
			y = "Armor +1 studded leather";
		else if(x <= 97)
			y = "Armor of resistance (studded leather)";
		else if(x <= 98)
			y = "Tome of clear thought";
		else if(x <= 99)
			y = "Tome of leadership and influence";
		else 
			y = "Tome of understanding";
		return y;
	}
	public static String I()
	{
		int x = roll(100,1);
		int z = 0;
		String y ="I";
		if (x <= 5)
			y = "Defender";
		else if(x <= 10)
			y = "Hammer of thunderbolts";
		else if(x <= 15)
			y = "Luck blade";
		else if(x <= 20)
			y = "Sword of answering";
		else if(x <= 23)
			y = "Holy avenger";
		else if(x <= 26)
			y = "Ring of djinni summoning";
		else if(x <= 29)
			y = "Ring of invisibility";
		else if(x <= 32)
			y = "Ring of spell turning";
		else if(x <= 35)
			y = "Rod of lordly might";
		else if(x <= 38)
			y = "Staff of the magi";
		else if(x <= 41)
			y = "Vorpal sword";
		else if(x <= 43)
			y = "Belt of cloud giant strength";
		else if(x <= 45)
			y = "Armor +2 breastplate";
		else if(x <= 47)
			y = "Armor +3 chain mail";
		else if(x <= 49)
			y = "Armor +3 chain shirt";
		else if(x <= 51)
			y = "Cloak of invisibility";
		else if(x <= 53)
			y = "Crystal ball (legendary version)";
		else if(x <= 55)
			y = "Armor +1 half plate";
		else if(x <= 57)
			y = "Iron flask";
		else if(x <= 59)
			y = "Armor +3 leather";
		else if(x <= 61)
			y = "Armor +1 plate";
		else if(x <= 63)
			y = "Robe of the archmagi";
		else if(x <= 65)
			y = "Rod of resurrection";
		else if(x <= 67)
			y = "Armor +1 scale mail";
		else if(x <= 69)
			y = "Scarab of protection";
		else if(x <= 71)
			y = "Armor +2 splint";
		else if(x <= 73)
			y = "Armor +2 studded leather";
		else if(x <= 75)
			y = "Well of many worlds";
		else if(x <= 76)
		{
			z = roll(12,1);
			if (z <= 2)
				y = "Armor +2 half plate";
			else if(z <= 4)
				y = "Armor +2 plate";
			else if(z <= 6)
				y = "Armor +3 studded leather";
			else if(z <= 8)
				y = "Armor +3 breastplate";
			else if(z <= 10)
				y = "Armor +3 splint";
			else if(z <= 11)
				y = "Armor +3 half plate";
			else 
				y = "Armor +3 half plate";
		}
		else if(x <= 77)
			y = "Apparatus of Kwalish";
		else if(x <= 78)
			y = "Armor of invulnerability";
		else if(x <= 79)
			y = "Belt of storm giant strength";
		else if(x <= 80)
			y = "Cubic gate";
		else if(x <= 81)
			y = "Deck of many things";
		else if(x <= 82)
			y = "Efreeti chain";
		else if(x <= 83)
			y = "Armor of resistance (half plate)";
		else if(x <= 84)
			y = "Horn ofValhalla (iron)";
		else if(x <= 85)
			y = "Instrument of the bards (Ollamh harp)";
		else if(x <= 86)
			y = "Ioun stone(greater absorption)";
		else if(x <= 87)
			y = "Ioun stone(mastery)";
		else if(x <= 88)
			y = "Ioun stone(regeneration)";
		else if(x <= 89)
			y = "Plate armor of etherealness";
		else if(x <= 90)
			y = "Plate armor of resistance";
		else if(x <= 91)
			y = "Ring of air elemental command";
		else if(x <= 92)
			y = "Ring of earth elemental command";
		else if(x <= 93)
			y = "Ring of fire elemental command";
		else if(x <= 94)
			y = "Ring of three wishes";
		else if(x <= 95)
			y = "Ring of water elemental command";
		else if(x <= 96)
			y = "Sphere of annihilation";
		else if(x <= 97)
			y = "Talisman of pure good";
		else if(x <= 98)
			y = "Talisman of the sphere";
		else if(x <= 99)
			y = "Talisman of ultimate evil";
		else 
			y = "Tome of the stilled tongue";
		return y;
	}
	
	public static int roll(int x, int y)
	{
		Random random = new Random();
		int z = 0;
		for(int i = 0; i < y; i++)
			z += (random.nextInt(x) + 1);
		return z; 
	}
}
